"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import environ
from pathlib import Path

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file if present.
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("PLATFORM_PROJECT_ENTROPY", default="unsafe-development-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.platformsh.site',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASE_CONFIG_SQLITE = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
}
DATABASES = {
    'default': DATABASE_CONFIG_SQLITE
}
if os.getenv('DB_HOST_POSTGRES') or os.getenv('DB_HOST_MYSQL'):
    print("Using database service from Platform.sh environment.")
    if os.getenv('DB_HOST_POSTGRES'):
        print("     * PostgreSQL")
        DB_ENGINE = 'django.db.backends.postgresql'
        DB_PASSWORD = env("DB_PW_POSTGRES")
    # if os.getenv('DB_HOST_MYSQL'):
    #     print("     * MariaDB/MySQL")
    #     DB_ENGINE = 'django.db.backends.mysql'
    #     DB_PASSWORD = ""
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': env("DB_NAME_POSTGRES"),
            'USER': env("DB_USER_POSTGRES"),
            'PASSWORD': DB_PASSWORD,
            'HOST': env("DB_HOST_POSTGRES"),
            'PORT': env("DB_PORT_POSTGRES"),
        },
        'sqlite': DATABASE_CONFIG_SQLITE
    }
else:
    print("Using local sqlite.")

# Caching
# https://docs.djangoproject.com/en/4.0/topics/cache/#django-s-cache-framework

if os.getenv('CACHE_LOCATION_MEMCACHED') or os.getenv('CACHE_LOACTION_REDIS'):
    print("Using caching service from Platform.sh environment.")
    # if os.getenv('CACHE_LOCATION_MEMCACHED'):
    #     print("     * Memcached")
    #     CACHES = {
    #         'default': {
    #             'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
    #             'LOCATION': env("CACHE_LOCATION_MEMCACHED"),
    #         }
    #     }
    if os.getenv('CACHE_LOACTION_REDIS'):
        print("     * Redis")
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': env("CACHE_LOACTION_REDIS"),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
if os.getenv('PLATFORM_APP_DIR'):
    STATIC_ROOT = os.getenv('PLATFORM_APP_DIR')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
